# cloudbuild.yaml

steps:
- name: gcr.io/cloud-builders/docker
  id: 'cloudbuild-android'
  env:
    - 'BUILD=$BUILD_ID'
    - 'PROJECT=$PROJECT_ID'
    - 'REV=$REVISION_ID'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/cloudbuild-android:${SHORT_SHA}',
    '-t', 'gcr.io/$PROJECT_ID/cloudbuild-android:latest',

    # These are used for Cloud Build variable substitutions (as shown in screenshot_01.png):
    # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
    #'--build-arg', 'ANDROID_SDK_PACKAGES="${_ANDROID_SDK_PACKAGES"}',
    #'--build-arg', 'GRADLE_WRAPPER_VERSION=${_GRADLE_WRAPPER_VERSION}',

    # The same, but with static values (no build-trigger configuration required)
    # When commenting these out, one has to run `./gradlew build` to fetch components
    # '--build-arg', 'ANDROID_SDK_PACKAGES=platform-tools platforms;android-30 build-tools;30.0.1 ndk;21.3.6528147',
    '--build-arg', 'ANDROID_SDK_PACKAGES=platform-tools platforms;android-30 build-tools;30.0.1',
    '--build-arg', 'GRADLE_WRAPPER_VERSION=6.1.1',

    # enable cloudbuild network
    '--network', 'cloudbuild',
    '.'
  ]

images:
- 'gcr.io/$PROJECT_ID/cloudbuild-android:${SHORT_SHA}'
- 'gcr.io/$PROJECT_ID/cloudbuild-android:latest'
